name: Roll pokemon every 2h

on:
  schedule:
    - cron: '0 0,4,8,12,16,20 * * *'

  workflow_dispatch:
jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run script
        env:
          ROMAIN_AUTH_TOKEN: ${{secrets.ROMAIN_AUTH_TOKEN}}
          LOGANN_AUTH_TOKEN: ${{secrets.LOGANN_AUTH_TOKEN}}
        run: python poke_roller.py
